name: Download UiPath CLI
description: 'Setup step that downloads the UiPath CLI'

inputs:
  version:
    required: false
    description: The version of the UiPath CLI that you want to download
    default: '25.1'

runs:
  using: "composite"
  steps:
    - name: Downalod UiPath CLI
      shell: bash
      run: |
        env=UiPath.CLI
        case "$OSTYPE" in
        msys*)    env=UiPath.Windows.CLI ;;
        cygwin*)  env=UiPath.Windows.CLI ;;
        *)        env=UiPath.CLI ;;
        esac
        echo env
    - name: Run curl
      shell: bash
      run: curl https://www.keycdn.com