# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Testing workflow

on:
    push:
        branches:
            ["main"]

jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
    test:
        needs: clone
        uses: ./action.yml